spring:
  profiles:
    active: local
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      javax:
        persistence:
          sharedCache:
            mode: ENABLE_SELECTIVE
      hibernate:
        cache:
          use_second_level_cache: true
          region:
            factory_class=org.hibernate.cache.ehcache.JCacheRegionFactory
  cache:
    jcache:
      config: ehcache.xml
custom:
  defaultLanguage: pl
