server:
  error:
    include-binding-errors: always
    include-exception: true
    include-message: always

spring:
  datasource:
    url: jdbc:mysql://89.171.139.92/oldtimers_rally
    hikari:
      username: apazurkiewicz
      password: Klonowa17@nyks
    driver-class-name: com.mysql.cj.jdbc.Driver
  jooq:
    sql-dialect: mysql

  jpa:
    database: mysql
custom:
  real-url: http://192.168.1.244:8080/
