spring:
  profiles:
    active: local
  security:
    filter:
      order: 10
  jpa:
    hibernate:
      ddl-auto: validate
    #    show-sql: true
    properties:
      javax:
        persistence:
          sharedCache:
            mode: ENABLE_SELECTIVE
        cache:
          config: classpath:ehcache.xml
      hibernate:
        javax.cache:
          provider: org.ehcache.jsr107.EhcacheCachingProvider
          uri: ehcache.xml
        cache:
          use_second_level_cache: true
          #          use_query_cache: true
          region:
            factory_class= org.hibernate.cache.jcache.JCacheRegionFactory
  cache:
    jcache:
      config: classpath:ehcache.xml
      provider: org.ehcache.jsr107.EhcacheCachingProvider
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 50MB
server:
  port: 8081
custom:
  defaultLanguage: pl
  jwtSecret: qwerty123
  jwtExpiration: 6000000
  jwtRefreshExpiration: 86400000
