server:
  error:
    include-binding-errors: always
    include-exception: true
    include-message: always

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/oldtimers_rally
    hikari:
      username: oldtimers_rally_spring
      password: asdszxc!dSzx
    driver-class-name: com.mysql.cj.jdbc.Driver
  jooq:
    sql-dialect: mysql
