server:
  error:
    include-binding-errors: always
    include-exception: true
    include-message: always
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/oldtimers_rally
    hikari:
      username: oldtimers_rally_spring
      password: asdszxc!dSzx
    driver-class-name: com.mysql.cj.jdbc.Driver
  jooq:
    sql-dialect: mysql
  jpa:
    database:
custom:
  defaultLanguage: pl
  jwtSecret: asdgfasdlbkjha123asdas!123sad&234ASDzxc
  jwtExpiration: 600000
  jwtRefreshExpiration: 864000000
  real-url: https://www.oldtimersweb.com/
  resource-location: photos
logging:
  level:
    org:
      springframework:
        web: info
      hibernate: info
  file:
    path: /opt/oldtimers/backend/logs
